version: '3.8'

services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: sanfer-db
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
